Traceback (most recent call last):
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
c = a.view()
print("ID of a is:", id(a))
print("ID of c is:", id(c))
np.share_memory(a,c)

c[3] = 62  #this changes also a
print(a)

print("ID of base array of c is:", id(c.base))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      2[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mID of a is:[39m[38;5;124m"[39m, [38;5;28mid[39m(a))
[1;32m      3[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mID of c is:[39m[38;5;124m"[39m, [38;5;28mid[39m(c))
[0;32m----> 4[0m [43mnp[49m[38;5;241;43m.[39;49m[43mshare_memory[49m(a,c)
[1;32m      6[0m c[[38;5;241m3[39m] [38;5;241m=[39m [38;5;241m62[39m  [38;5;66;03m#this changes also a[39;00m
[1;32m      7[0m [38;5;28mprint[39m(a)

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/numpy/__init__.py:311[0m, in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    308[0m     [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mtesting[39;00m [38;5;28;01mimport[39;00m Tester
[1;32m    309[0m     [38;5;28;01mreturn[39;00m Tester
[0;32m--> 311[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124m"[39m[38;5;124mmodule [39m[38;5;132;01m{!r}[39;00m[38;5;124m has no attribute [39m[38;5;124m"[39m
[1;32m    312[0m                      [38;5;124m"[39m[38;5;132;01m{!r}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat([38;5;18m__name__[39m, attr))

[0;31mAttributeError[0m: module 'numpy' has no attribute 'share_memory'
AttributeError: module 'numpy' has no attribute 'share_memory'

