Traceback (most recent call last):
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

# read data from file
df = pd.read_csv("data/world-bank-1_data.csv")

# check the size of the DataFrame
print(df.shape)

# calculate the population density
df["population_p"] = df["population_t"]/df["land_area"]

# check the size of the DataFrame again
print(df.shape)

# check the first few rows
head(df)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [1], line 16[0m
[1;32m     13[0m [38;5;28mprint[39m(df[38;5;241m.[39mshape)
[1;32m     15[0m [38;5;66;03m# check the first few rows[39;00m
[0;32m---> 16[0m head(df)

[0;31mNameError[0m: name 'head' is not defined
NameError: name 'head' is not defined

