Traceback (most recent call last):
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

x = df["life_expectancy_t"].to_numpy()
y = df["co2_emissions_pc"].to_numpy()
x_highlight = highlight["life_expectancy_t"].to_numpy()
y_highlight = highlight["co2_emissions_pc"].to_numpy()
highlight = df[df["co2_emissions_pc"] > 40]
ax.scatter(x, y,  facecolor="black")
ax.scatter(x_highlight, y_highlight, facecolor="red")
fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [14], line 7[0m
[1;32m      5[0m x [38;5;241m=[39m df[[38;5;124m"[39m[38;5;124mlife_expectancy_t[39m[38;5;124m"[39m][38;5;241m.[39mto_numpy()
[1;32m      6[0m y [38;5;241m=[39m df[[38;5;124m"[39m[38;5;124mco2_emissions_pc[39m[38;5;124m"[39m][38;5;241m.[39mto_numpy()
[0;32m----> 7[0m x_highlight [38;5;241m=[39m highlight[[38;5;124m"[39m[38;5;124mlife_expectancy_t[39m[38;5;124m"[39m][38;5;241m.[39mto_numpy()
[1;32m      8[0m y_highlight [38;5;241m=[39m highlight[[38;5;124m"[39m[38;5;124mco2_emissions_pc[39m[38;5;124m"[39m][38;5;241m.[39mto_numpy()
[1;32m      9[0m highlight [38;5;241m=[39m df[df[[38;5;124m"[39m[38;5;124mco2_emissions_pc[39m[38;5;124m"[39m] [38;5;241m>[39m [38;5;241m40[39m]

[0;31mNameError[0m: name 'highlight' is not defined
NameError: name 'highlight' is not defined

